### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by pr4deepr** [AntonotnaWang/3DCellSeg#1]
Hi
  Thanks for making this repo available. 
Could you list dependencies as a requirements.txt or environment.yml file so its easy to configure and work with 3DCellSeg,?

Cheers
Pradeep

**Comment by AntonotnaWang** [comment]
Dear Pradeep,

Thanks for your suggestion. I have uploaded requirements.txt.

Best
Andong

**Comment by pr4deepr** [comment]
Hi Andong

Thanks for the prompt response. One more suggestion or request.

Is it possible to also include the exact versions of each library or dependency you've used? 
It could even be in a separate file. 
It may not matter now, but it will save a lot of time in the future when trying to figure out dependencies a few versions old.

Cheers
Pradeep
